spring.datasource.url=jdbc:postgresql://localhost:5432/hotels_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

cloudinary.cloud_name=dolqrhd66
cloudinary.api_key=165451449161488
cloudinary.api_secret=jVGxRoCKv2yiN2_bZyOILFBGATI




