# =========================
# DATABASE CONFIGURATION
# =========================

# Se DB_URL não estiver definido, usa o banco local com SSL desabilitado
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/hotels_db?sslmode=disable}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / HIBERNATE SETTINGS
# =========================

# Atualiza automaticamente o schema do banco (create/update)
spring.jpa.hibernate.ddl-auto=update

# Mostra queries SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialeto do PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================
# SERVER PORT
# =========================

# Porta do servidor: usa variável de ambiente Render, padrão 8080 local
server.port=${PORT:8080}

cloudinary.cloud_name=dolqrhd66
cloudinary.api_key=165451449161488
cloudinary.api_secret=jVGxRoCKv2yiN2_bZyOILFBGATI




